### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by nip10** [grrr-amsterdam/grrr-utils#5]
There's already a config file for Travis CI, but it isn't configured on their end.

**Comment by harmenjanssen** [comment]
We're working on it, but somehow the repo isn't showing up in the list over at Travis. 😖
I'm still not sure what's wrong there...

**Comment by harmenjanssen** [comment]
Fixed in 9787c807cfe9ea78504f20db1f70e8af61dadd2d.
